# Production profile
spring:
  # Database (через переменные окружения)
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  # Email
  mail:
    host: ${EMAIL_HOST}
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Production logging
logging:
  level:
    root: WARN
    kz.arannati: INFO