# Production profile
spring:
  # Database (через переменные окружения)
  # Note: DATABASE_URL should include "?currentSchema=arannati" parameter
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: arannati

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
    default-schema: arannati
    parameters:
      schema: arannati

  # Email
  mail:
    host: ${EMAIL_HOST}
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Production logging
logging:
  level:
    root: WARN
    kz.arannati: INFO
