# Development profile
spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/arannati?currentSchema=arannati
    username: "arannati_user"
    password: "280904"
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: arannati

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
    default-schema: arannati
    parameters:
      schema: arannati

  # Email (для разработки - консоль)
  mail:
    host: localhost
    port: 1025
