# General settings
spring:
  application:
    name: "Arannati"
  profiles:
    active: dev

  # FreeMarker
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/

  # File upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Enable ANSI output
  output:
    ansi:
      enabled: ALWAYS

# Server
server:
  port: 8080

# Logging
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  charset:
    console: UTF-8
